import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Entertainment Web App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="bg-prime-dark fixed top-0 w-full sm:max-w-[95vw] sm:m-5 sm:rounded-lg md:w-fit md:h-[95vh]">
          <Navbar />
        </header>
        <main className="mt-20 mx-5 md:mt-10 md:ml-28">{children}</main>
      </body>
    </html>
  );
}
